### ISSUE TITLE
Feature Port Request

### ISSUE THREAD

**Issue by AsaiasWolffe** [Skyrat-SS13/Skyrat-tg#1208]
Please port the wireless cell chargers and also the mining techs. When I first looked at snowbox I immediately got excited for the possibilities of what a mining tech can do with a multi z level mining base to play with. Also since fauna are more gnarly on tg I can see the base getting damaged-destroyed more often than on the current server

**Comment by atakiya** [comment]
Wireless chargers might come back in another way.
Mining techs are not coming back simply due to the fact that there's no point currently, xenoarch isn't there either.

Also for the future: please keep feature port requests on one topic per issue, this gives a better overview and managability, thank you!
