### ISSUE TITLE
"Snout" sprites are rendered in front of "Head" markings

### ISSUE THREAD

**Issue by CameronWoof** [Skyrat-SS13/Skyrat-tg#1315]
The snout sprite should be a base the head marking is drawn over, otherwise details like mouths or teeth get buried underneath the base snout shape. Alternately, make it possible to order them yourself.

**Comment by Azarak** [comment]
Which snouts / markings did you encounter that issue with? I dont think that was ever the case, they.. oh right. It was the markings that were rendered above the snout, which now they are rendered alongside bodyparts. Snouts usually have variants for when you want them rendered on the TOP or ADJACENT layer, to layer differently with other accessories or hair. 

Potentially you could have an option to have a snout rendered alongside bodyparts, instead of mutant bodyparts. 

Or you could adjust the couple markings/snouts that feel wrong now. Which snout/markings specifically were wrong?
I had also done some manual work on the sprites, and I coulda made some mistakes. Generally you'll see things are much brighter and clearer now.

**Comment by CameronWoof** [comment]
The Otie head marking renders below the Otie snout, causing the head marking (it's a cute lil' mouth) not to show. Ideally, the snout would provide the base and the head marking would layer on top of it to provide additional detail.

**Comment by whataboutism** [comment]
This is also the case for synthetic lizardperson snouts and all head markings! It makes it so you really only get to use markings on the back and top of the head.

**Comment by Gandalf2k15** [comment]
This has been fixed.
