### ISSUE TITLE
Polychromic are donator items?

### ISSUE THREAD

**Issue by IgiariValkyr** [Skyrat-SS13/Skyrat-tg#1320]
![2020-10-15_00-40-32](https://user-images.githubusercontent.com/5521322/96081553-220f5e00-0e7f-11eb-84a1-58adf9b7eecf.png)

...wanna talk about it?

**Comment by Azarak** [comment]
All things are subject to change, the polychromic cloaks arent donator restricted for example. 
I understand that if items were previously available and now they're not, that kind of sucks, and I share the opinion.
Im not a fan of Xyel needing to pay extra because the patreon money doesn't cover hosting and I'm trying to find some decent incentivizes for people.

**Comment by Owai-Seek** [comment]
Citadel did it by allowing people to do a (one time) cosmetic for like... 15 dollars? A lot of those cosmetics got transferred from donator only, to everyone being able to use them.

I think certain items being donator only in the loadout (as long at it doesn't give advantages) is fine, as long as they're available ingame as well. (At that point, it's just a convenience thing.)

**Comment by Azarak** [comment]
They're freely available now
