### ISSUE TITLE
[KAPULIMBS] digitigrade families gear

### ISSUE THREAD

**Issue by RatFromTheJungle** [Skyrat-SS13/Skyrat-TG#13225]
The Families 'suit'(or armor) slot stuff causes digitigrade to break, namely, the powderganger jacket (if you leave it on for too long, even your legs will revert to plantigrade until respawned)

**Comment by GoldenAlpharex** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
this sounds like a kapulimbs moment

**Comment by vinylspiders** [comment]
@Jolly-66 another one that is closeable I think.

I have been sitting around on my test server with these jackets on and no issues.

Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/15353 it seems. 

![image](https://user-images.githubusercontent.com/13398309/229034804-168c8728-0f3b-4abd-a7c9-799e6d0e1e75.png)
