### ISSUE TITLE
Cargo Fishing Poles are non-functional

### ISSUE THREAD

**Issue by Rvali** [Skyrat-SS13/Skyrat-TG#14468]
Reporting client version: 514.1584

## Round ID:
5757

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Disables bureaucratic error](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14290)
- [Mutant touchups](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14431)
- [Window Airbags (also refactors inflatables)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14446)
- [Emergency Spacesuits](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14455)

## Reproduction:

The bought fishing pole from cargo does not work with fishing whatsoever. This has been tested with normal bodies of liquid and with water basins.
Crafted fishing poles are functional with water basins and bodies of liquid.

Confirmed and tested above with admins, and does occur under normal circimstances.

**Comment by YakumoChen** [comment]
The problem is that there are now two different systems for fishing. Cargo poles only work in select fishing spots (including lavaland and fishing portals you have to get). Skyrat fishing uses basins and is not coded in any way for cargo fishing.

Not a bug, just two systems poorly coded into the game.
