### ISSUE TITLE
Excitable quirk is toggleable

### ISSUE THREAD

**Issue by Jolly-66** [Skyrat-SS13/Skyrat-TG#15082]
## Round ID:
6034

## Reproduction:
Be excitable.
Get head pat.
Wag.
Get head pat again.
Stop wagging.

**Comment by ghost** [comment]
This is an issue caused by the *wag emote itself, in that using it while wagging is what turns it off. So, with excitable, being patted while wagging makes you *wag, which, since you're wagging, STOPS your wagging.
Best fix would be a check on the excitable-headpat if you're wagging, and if you already are, DONT *wag so you dont stop wagging.

Wag no longer looks like a word, not one thats appropriate. Damn you.

**Comment by Jolly-66** [comment]
Actually an upstream issue it seems with *wag

https://github.com/tgstation/tgstation/issues/68799
