### ISSUE TITLE
AI's are able to target off-Z RCD and RCD Subtypes

### ISSUE THREAD

**Issue by Zenitheevee** [Skyrat-SS13/Skyrat-TG#15274]
## Testmerges:

#13848 
#14023 
#14593 
#15028 
#15092 
#10823 

## Reproduction:

Be Malf AI
See ARCD (A subtype not able to be spawned on station currently, and only used on a few station roles) That you can explode
Click it because its funny and be unable to watch it blow someone's leg off because it actually blew off the leg of someone deep in space

**Comment by YakumoChen** [comment]
not a bug
RCD detonation targets ALL instances of RCDs. Otherwise it would lead to someone just hiding an RCD on lavaland or something and using it to fuck with the AI, or have problems with multi-Z. Or industrial RCDs still eating through rwalls because of course an ERT needs to be able to effortlessly kill the AI.

Blowing up admin RCDs is generally a non-issue since admins can always just spawn another.

**Comment by Zenitheevee** [comment]
Upstream issue, Someone is also already working on it.

**Comment by Zenitheevee** [comment]
> not a bug RCD detonation targets ALL instances of RCDs. Otherwise it would lead to someone just hiding an RCD on lavaland or something and using it to fuck with the AI, or have problems with multi-Z. Or industrial RCDs still eating through rwalls because of course an ERT needs to be able to effortlessly kill the AI.
> 
> Blowing up admin RCDs is generally a non-issue since admins can always just spawn another.

The main issue is this blows up EVERYWHERE, Including ghost role Z's deep in space and CC Zlevels.

**Comment by YakumoChen** [comment]
> Including ghost role Z's deep in space and CC Zlevels.

Sucks to be a ghost role deep in space, but the station's the main event, and being able to subvert the whole (one use) point of destroy RCDs potentially is bad.
