### ISSUE TITLE
Entertainment Monitors (Thunderdome) being borderline useless

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#15307]
## Round ID:
6114

## Reproduction:
You can click on it from any range, probably to allow you and the boys at the bar to watch the ultrabowl from the bar, but even when it comes on, you click it and you dont even get a window to watch, im assuming its an admin thing where they allow you to watch it but nobody enables it **_ever_**, so its just taking up wall space.

**Comment by YakumoChen** [comment]
this an upstream bug, I'm fairly sure.

**Comment by Jolly-66** [comment]
To quote someone from upstream on a PR (that has been attempted twice), since the camera can't be physically "disconnected" or "shut off", players can see the admins fucking around and thats something [We] don't want to be seen all the time.

Had the TV studios PR went through, I think they would've had a purpose.
