### ISSUE TITLE
Play Internet Sound always fails with a Youtube-dl JSON parson FAILED message with an unknown value of ":"

### ISSUE THREAD

**Issue by ArdentSpark** [Skyrat-SS13/Skyrat-TG#15364]
Reporting client version: 514.1585

## Round ID:
6146

## Reproduction:
Try to play an internet sound (youtube link or soundcloud link)
It will result in a error as follows:
Youtube-dl JSON parsing FAILED:
Unknown value:                               :

**Comment by GoldenAlpharex** [comment]
This is an issue because we haven't ran certain installation scripts on the dockerless instance of the server, which is currently hosting the server you're playing on. It'll come back to normal as soon as we switch back to the docker instance, which should hopefully not take too long. Maybe a few days.
