### ISSUE TITLE
Paramedic winter coats cant equip crew monitor in suit storage

### ISSUE THREAD

**Issue by Sweettoothart** [Skyrat-SS13/Skyrat-TG#15532]
Reporting client version: 514.1583

## Round ID:
6211

## Testmerges:
- [[MODULAR] [HOST REQUEST] Pixel Shift Out of the Way!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15175)
- [Disables progtots](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13970)
- [Early mirror of #69106](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15527)

## Reproduction:
put on the jacket, try to equip a handheld crew monitor in the suits storage, cry because you cant and put it in a pocket instead.

**Comment by Jolly-66** [comment]
I don't know what the exact issue here, speaking as someone who plays paramedic constantly, I went ahead and tested this on a fresh recompile of master.

![image](https://user-images.githubusercontent.com/70232195/184153043-a34279f3-028e-4c7e-8424-67070ffdd56f.png)

It works, but I want to assume something wasn't right on your end.
Are you sure you had the jacket and jumpsuit on? If you only had your jumpsuit on, you can't put things in the suit storage since, well, you don't have a "suit".

If this issue remanifests please let me know.
