### ISSUE TITLE
AI can see stuff it shouldn't

### ISSUE THREAD

**Issue by Diltyrr** [Skyrat-SS13/Skyrat-TG#15595]
## Reproduction:

Playing AI on Delta Station, I was able to track and see both the "syndicate salvage pilote" and "jonesy" through the cameras located near them

**Comment by Jolly-66** [comment]
This can be a handful of things,

1. Upstream moment
2. Someone made a camera and didn't set the network properly (I don't blame you guys for not knowing, you really need to be a mapper to understand the networks
3. Mapper moment

Regardless if this happens again or not, asking from the code side, be a good individual and don't try to annoy the others, it'll be for the better (since this is certainly an oversight, should it be an us thing with maps)

**Comment by Zergspower** [comment]
player ooc issue - and an upstream coding one
