### ISSUE TITLE
Unpowered airlocks disappear underneath catwalk floors during power surge event

### ISSUE THREAD

**Issue by Tailiik** [Skyrat-SS13/Skyrat-TG#16007]
## Reproduction:
1. Load up tram
2. Adminspawn/wait for power surge event
3. Crowbar it open
4. Airlock disappears behind catwalk floor sprite, making it so you have to alt click the tile to close it again

I tried to depower airlocks myself using a multitool as well as asking a cyborg to depower them before opening them, and nothing seemed to trigger the sprite to disappear outside of the power surge event where apcs need to be restarted. Relevant screenshot where the airlock edges become invisible below. (Not sure how to embed on github, wouldn't mind being shown how)

https://i.imgur.com/KnRsIdh.png

**Comment by ghost** [comment]
Is it really only during the power surge event? Powerless airlocks dont do it, only powersurge-shutoff ones??
If so I'm gonna cry

Either way, this would likely be an upstream issue considering the tiles/doors are theirs, BUT we could be missing a door icon state or some cursed shit so it'll need to be tested

**Comment by Tailiik** [comment]
I'm fairly certain it only happens during the surge event, because during the surge the depowered airlocks disappeared, but when I was testing it later in the round by just hacking the power off they didn't disappear.

**Comment by Zergspower** [comment]
> I'm fairly certain it only happens during the surge event, because during the surge the depowered airlocks disappeared, but when I was testing it later in the round by just hacking the power off they didn't disappear.

So I ran bot the Supermatter Surge and the Grid Check event (surge i assumed meant gridcheck but did both anyway). The door didnt disappear but I may have a reason behind it - Tram in particular has an issue with sprite movement due the Tram itself, it's why you'll sometimes see, say, a pirate ship parts still there even though they've moved - so i'm leaning towards Tram's buggy sprite update issue for causing this to happen rather than it being a map or spriting issue all together.
