### ISSUE TITLE
[Minor] Icebox Mining spawns a bit wrong

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat-tg#1633]
Issue reported from  Round ID: [20](https://scrubby.melonmesa.com/round/20) (Skyrat SS13 - /TG/ Anthro-Friendly Roleplay Server [Apply on Discord, Weekly Events])

Reporting client version: 513.1536

![dreamseeker_ktZJR2rYRl](https://user-images.githubusercontent.com/49801705/98463837-02204100-2184-11eb-848a-e9564453e58d.png)

Cannot say if this is consistent or a fluke. The ladder does allow access to and from the lower level without issue. I expect this is just icebox being improperly prepared for our mining outpost.
Other exits on this level are sealed in by snow, but otherwise passable.

**Comment by atakiya** [comment]
This is more or less intended.
**Parts of the maps are randomly generated at round start.**
We could probably put a safezone around but.. To be fair, it's just possible to move the exit a bit below manually as this will not happen every round.

Closing due to above. If you wish to request a change of it however, feel free to reopen to discuss on why.
