### ISSUE TITLE
Safe Cracking with a Stethoscope does not produce noise messages.

### ISSUE THREAD

**Issue by W4rd3nn** [Skyrat-SS13/Skyrat-TG#16575]
## Round ID: 
6636

## Testmerges:

- #16019 
- #16468 
- #16290 
- #16574 

## Reproduction:
Safe cracking does not appear to be possible at the moment. Attempting to use a stethoscope on the safe only produces messages when the dial is turned left or right by 10 or 50, upon which it reports "The sounds from the safe are too fast and blend together." 

However, when turning the dial by one, it will not produce any sound. No klunks or plunks when reaching the correct number. I have tested this with both the safe in the Freighter's secure storage and the floor safe in a derelict in space. I have not tested this with the station safe, however. My guess is that either there is an issue with the code that produces the klunk messages, or there is an issue initializing the correct numbers altogether. 

Additionally, the UI isn't that great. Pressing the "left" buttons turns the dial right, and vice versa.

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/193427930-e91226ee-0e8e-45c2-8ecd-30a40d0ead9d.png)
 looks like the noises were moved to a popup prompt but are working as intended, as for the 10 or 50 comment that's due to you not being able to track the motions - you still need to go 1 at a time to dial in the actual code
