### ISSUE TITLE
Engineering Guard Uniform Sprite Missing

### ISSUE THREAD

**Issue by SmolGreenBuggo** [Skyrat-SS13/Skyrat-TG#17235]
Reporting client version: 514.1588

## Round ID:
6854

## Testmerges:
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [new rituals](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16942)
- [change how ashwalker's revive + more](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16902)
- [Near complete refactor and rework of how forge crafting benches work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
- [Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)
- [Fix/Refactor: MOD tails, tails use defines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16778)

**Comment by Jolly-66** [comment]
@OrionTheFox

**Comment by ghost** [comment]
Fixed by #16892, currently Test Merged; if this still occurs RIGHT NOW (Nov. 5th) please ping me in discord because it means that the mentioned PR also has the issue

Also technically a duplicate of #17146 but that's TF4's fault for not naming the items themselves in that report as keywords :trollface:
