### ISSUE TITLE
Simple mobs being picked up still breaks chat

### ISSUE THREAD

**Issue by tobjv** [Skyrat-SS13/Skyrat-TG#17279]
Reporting client version: 514.1589

## Round ID:
6869

## Testmerges:
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Near complete refactor and rework of how forge crafting benches work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
- [Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)
- [Fix/Refactor: MOD tails, tails use defines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16778)
- [Gives the lavaland ashwalker den the same treatment I gave the icebox one](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)

## Reproduction: If you pick up a mob and put them down it breaks their chat. So far applies to Cat, Dog, Fox, Bunny and PAI
Yes this is a repeat report.

**Comment by DannyBoy3642** [comment]
This also applies to Borers in my experience.

**Comment by DannyBoy3642** [comment]
Update in reproduction: I've noticed that this seems to trigger for pAI under the following conditions:
- You are folded out, meaning you are currently using your holochassis (cat, mouse, etc.) rather than being a plain pAI.
- You are picked up by someone and held in one of their hands.
- You are dropped for any reason. For ANY reason, even if the player drops you intentionally. ~~other than the player dropping you intentionally (walking out of their hands, falling, fainting, etc.)~~
- Also seems to happen if you're placed on the head and fold in your chassis, probably many more ways to trigger it.
And can be solved by having the player wipe the pAI and re-download you.

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/commit/ec2aad19d2f739857c3d101376ddf506ab9d47e9 Fixed @lessthnthree

**Comment by lessthnthree** [comment]
Fixed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/18474
