### ISSUE TITLE
Recolorable standalone hood hides mutant ears when paired with face items

### ISSUE THREAD

**Issue by kittysmooch** [Skyrat-SS13/Skyrat-TG#18329]
Reporting client version: 514.1589

## Round ID:
7287

## Reproduction:
Have meow meow kitty ears. Wear the standalone hood. Put almost any item on your face slot and be amazed as your ears miraculously disappear. Nearly everything that can equip to your face triggers this behavior, including pipes and lollipops, but notably not the three hole balaclavas.

**Comment by theselfish** [comment]
This is a TG issue, or at least some sort of hood issue in general.
Happens with the mining hood. Which makes mining without a cape or big neck piece/tail/wings/etc a 60% chance of turning into a very funny looking legion corpse.

**Comment by ghost** [comment]
Flags throwing a fit, possibly NOT a TG issue: balaclava has a flag specifically to allow ears to appear, 3hole probably inherits it, and I accidentally coded it to force the ears thru even if the hat above the mask should hide.... (I need 2 fix that)

Though I wonder why the hood only has the issue when paired with a mask?

**Comment by vinylspiders** [comment]
![dreamseeker_qPBBn2JyzC](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/22b0c645-b965-4de4-b02c-bc45d49dcc8b)

![dreamseeker_039KdDEvtg](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/171dc517-6739-4a95-b93a-5b0391794fad)

Lollipops and pipes aren't hiding ears anymore.

Standalone hood still does this, but that is intentional as it has the HIDEHAIR and HIDEEARS flag. Closing this.
