### ISSUE TITLE
MediBorg cannot transfer body to surgical table

### ISSUE THREAD

**Issue by LimblessLayabout** [Skyrat-SS13/Skyrat-tg#1847]
Issue reported from  Round ID: [47](https://scrubby.melonmesa.com/round/47) (Skyrat SS13 - Anthro-Friendly Roleplay Server [Apply on Discord, Weekly Events])

Reporting client version: 513.1536

as title.

**Comment by SpookyTheFox** [comment]
This has been a forever issue, it was on the old server too. Semi-intentional. Medborg has flawless surgery regardless of table or not (or should anyway, haven't tested on the rebase) so you do not need to put them on a table. You can operate with 100% success rate on the roller bed that medborg carries, and since that does not block movement, you can easily drag and then buckle people to it.

**Comment by atakiya** [comment]
Seems intentional in that case. Closing therefore.
Feel free to reopen if the medborgs can't operate properly.
