### ISSUE TITLE
Permit HUD glasses and wing layer issues

### ISSUE THREAD

**Issue by DiscordWizard** [Skyrat-SS13/Skyrat-TG#18727]
## Issue:

Permit HUD glasses that you spawn with as a customs agent are always facing forwards, no matter where you turn the icon is the forwards facing glasses icon

Dragon Alt 2 wings and I think other wings are clipped behind the drake taur body instead of going over it. It looks all kinds of goofy

## Reproduction:

Play with a Drake taur body and Dragon Alt 2 wings, and put on the glasses you start with as a customs agent

**Comment by vinylspiders** [comment]
Fixed the glasses, but the wings issue seems to be an issue with all wings. It's just more visible on some than others (Try 'beetle' and similar small wing types--they do not show at all because they are completely behind the taur body layer). 

May want to make a separate issue just for that. It would require rewriting the way taur body sprites are layered and rendered.
