### ISSUE TITLE
Crusader's Belt Pouch MIA (take 2)

### ISSUE THREAD

**Issue by sciira** [Skyrat-SS13/Skyrat-TG#18733]
## Round ID:
Unknown

## Date and Time of Issue:
Issue first noticed sometime after 6:00pm EST, 1/13/23

## What Map did this Issue occur on:
First noticed on voidraptor - issue persists on all maps

## Testmerges (If Applicable):
Unknown

## Reproduction:
- create crusader's belt 
(tool belt, leather, cloth, iron, gold, welder, screwdriver, wirecutters)

Crusader's belts -once created- are made missing their storage pouches, thus effectively nullifying their use as a combination storage item/bladed weapon holster. As-is, belts can now hold two bladed weapons in the scabbard. Sprite indicating weapon is in the belt will not update until the 2nd weapon is added, cannot draw weapon using alt+click until a second weapon is in the belt.

## Possible Screenshots of the Issue in question:
https://cdn.discordapp.com/attachments/640760727489085450/1063697954122252429/image.png

**Comment by YakumoChen** [comment]
likely a product of the storage refactor

**Comment by vinylspiders** [comment]
![image](https://user-images.githubusercontent.com/13398309/213869650-9050b2f0-c0b7-4472-a91c-9eb37a36653a.png)

I've tried to recreate this but can't. Is it still an issue? If so what are the exact steps you are taking to cause it? 

Any details about your character's species, etc may be relevant. I was testing with a normal human.

**Comment by sciira** [comment]
@vinylspiders 

I played as a hemophage when I made it but two people who I regularly watch do smithing made them too and encountered the same error, and both of them were synths. 

Is it possible its to do with the difference between spawning in the belt and crafting one?

also: its possible this has since been fixed, I haven't played in a few days so this might be resolved by now. I'll have a whirl at it here in a bit to find out

**Comment by vinylspiders** [comment]
@sciira aaah! Crafting. Yeah, okay. luckily I just spent the last few hours in crafting code fixing an unrelated bug and immediately know the cause.

The belt is supposed to have the pouch inside upon its spawning. 

But in crafting code, whenever a new item is made it deletes any contents of items that have been created by the item spawning. So that is what is happening to the pouch. It gets created when the belt spawns, then is immediately destroyed by the crafting system. That is why spawned belts are unaffected, because they are untouched by the crafting system.

Thankfully there is a rather easy way to create it again and I will code that in for you right now.
