### ISSUE TITLE
[bug] "Remote cleaning can negatively affect"

### ISSUE THREAD

**Issue by Ddanik** [Skyrat-SS13/Skyrat-TG#18765]
Round ID: 5116
BYOND Version: 514.1589
Server revision compiled on: 2023-01-10T22:00:42+00:00
Master commit: [b44967501c7bd25e05326ef0302568d8e40a898f](https://github.com/Skyrat-SS13/Skyrat-tg/commit/b44967501c7bd25e05326ef0302568d8e40a898f)
The following pull requests are currently test merged:

So, ran into a bug. During the gravity anomaly, if you remove traces of blood, dirt and other debris from the floor, and the character is still flying into the distance, the action does not stop. I haven't tested with other actions like: Feed, water, or take something off of another character, but the problem is

**Comment by vinylspiders** [comment]
Do you mean the progress bar kept going forever and you couldn't cancel it, or it just kept going and then finished as normal?

Because if it's the latter then that is coded like that intentionally. Normally if you move your character the progress bar will stop and the action will be canceled, but if your movement comes from 'drifting' aka involuntary movement from lack of gravity, the action is allowed to continue. 

https://github.com/Skyrat-SS13/Skyrat-tg/blob/edb759bbd2832c16537e3b1ddf263364ff99f8f0/code/__HELPERS/mobs.dm#L273-L281

**Comment by Jolly-66** [comment]
May be a /tg/ thing with movement, leaving it as this for now.

**Comment by vinylspiders** [comment]
> May be a /tg/ thing with movement, leaving it as this for now.

This was bothering me, so I decided to personally test it.
It could be that they were just lagging, and saw the progress bar keep going. Or they might just not understand how the progress bar is supposed to work. It's hard to say because they never answered the followup questions.

But from my testing I can say with confidence that the bar correctly stops when you are moved by the gravitational anomaly, just as it does when you move normally.

This can be safely closed. @Jolly-66
