### ISSUE TITLE
Connecting an Ore Silo to an ORM seems to delete all contents.

### ISSUE THREAD

**Issue by Green-Horns** [Skyrat-SS13/Skyrat-tg#1881]
## Round ID:

 Can't remember

## Reproduction:

 As a free golem, I built an ore silo which was then connected to the ORM by another free golem. In doing so, it seemed to delete anything contained within. This did not happen with any of the other machinery that was synched, like the circuit printer or Protolathe.

**Comment by Azarak** [comment]
I cant seem to reproduce this. The ORM ejects its ores as it links

**Comment by EvilCrimsonWitch** [comment]
I believe this issue is directly caused by the ice box map having a pre-existing link on the golem ships ORM to the stations ore silo. When the golems create their own silo and link it up, they're essentially creating their own network, which causes all previous resources they've deposited into the stations ore silo to be removed from their access.

**Comment by Zergspower** [comment]
Unable to recreate - issue I believe has either been patched or corrected over time.
