### ISSUE TITLE
DNA Infuser does not modify organs following the recent changes.

### ISSUE THREAD

**Issue by kylecorn1996** [Skyrat-SS13/Skyrat-TG#19041]
## Round ID:
7544

## Reproduction:
The DNA infuser does not apply organ changes following the 24th of january skyrat specific DNA infuser changes. tested with carp corpses, playing a "humanoid" character with vanilla organs.

**Comment by Jolly-66** [comment]
@Floofies

**Comment by Nechronom** [comment]
it's april 27th I can't seem to get rat or gondola mutations to work properly, either

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20650/files

Seems to be fixed, confirmed in my testing.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/32b9fcd7-8ce4-477d-a29c-6f968651067f)

If there is something that I am missing please let me know with more information on how to reproduce and I'll reopen this.

**Comment by Nechronom** [comment]
Apologies for wasting your time, yes it does appear to function. Unfortunately I came to realize sometime ago that I believe the issue was more that I had cybernetic eyes that were not being replaced by the appropriate organs, therefore not allowing the entire process to be completed. Which seems intentional, and is much easier to rectify

**Comment by vinylspiders** [comment]
> Apologies for wasting your time, yes it does appear to function. Unfortunately I came to realize sometime ago that I believe the issue was more that I had cybernetic eyes that were not being replaced by the appropriate organs, therefore not allowing the entire process to be completed. Which seems intentional, and is much easier to rectify

No worries!
