### ISSUE TITLE
Some change that deleted/no longer allows an overlay over the front of the body

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#19909]
## Reproduction: I believe the Drake Bone used to overlay over the chest and belly of a character, but was recently changed to go from the back up and over the neck slightly. While I'm sure this change is fine, there is no means to have the overlay over the chest and belly, just the belly.
In the example image, the black over the chest and belly served as a very useful way to represent dragon plates, or lizard scales, of which would be a different varying color on the belly of a scaly creature.
![Ekeci-The-Great-Ashen Image](https://user-images.githubusercontent.com/59770685/225759481-4d45e838-a868-4424-bb97-3ec8d0e7081f.JPG)

**Comment by Erokusan** [comment]
I've looked more into this, and I've come to realize, it's actually due to the fact that the Body Marking option is no longer existent in the character creation panel.

**Comment by vinylspiders** [comment]
The Drake bone's always been like that since it was added in https://github.com/Skyrat-SS13/Skyrat-tg/pull/969.

The one in your screenshot is called 'Light Belly' and it was just moved to a new spot by a recent refactor.

![image](https://user-images.githubusercontent.com/13398309/228802965-ee722fc6-c537-40be-be95-b4b4fde464b2.png) 

Make sure this is checked, then go into Augments+ and it'll be there!

![image](https://user-images.githubusercontent.com/13398309/228803273-9013572f-d01d-4357-8b8c-9a136bb948aa.png)

@Jolly-66 can be closed.
