### ISSUE TITLE
Janitorial Borgs Auto-Wash function working for a split second only

### ISSUE THREAD

**Issue by MixMashy** [Skyrat-SS13/Skyrat-TG#20706]
Reporting client version: 514.1589

## Round ID:
8159

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[MOSTLY MODULAR] Time Clock](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)

## Reproduction:
Press Auto-wash verb HUD button.. split second later.. Doesnt do anything but make the noise of startup. Staff tested inside Thunderdomb aswell. Same result

**Comment by vinylspiders** [comment]
Could I please get some more information about this? Because in my testing I was not able to reproduce.

You said it made the audio sound--was it also doing the shaking animation like shown below?
Were there any balloon alerts that popped up on the screen? 

Your bucket had water in it right? It won't work if you don't.

Just trying to figure out the point at which the function stopped running because nothing in the code immediately jumps out at me. Any details like that are helpful!

![dreamseeker_iPRSYwvMPb](https://user-images.githubusercontent.com/13398309/233853941-10ce9bac-fc0d-45e9-8779-6d281b827186.gif)

**Comment by Thlumyn** [comment]
I had that same issue in that round. Bucket did have water. The status bar for turning on autowash would pop up but would go away after only a couple pixels of progress with no sort of error message or anything.

**Comment by vinylspiders** [comment]
If it is as you say--no balloon alerts saying "activation canceled" or any other message, then that indicates that it's caused by the `do_after` (the progress bar thing) canceling (or a runtime, but Golden checked the logs and couldn't find any runtimes related to this--though it is possible we missed something). 

Usually `do_after` gets canceled when you move or equip/unequip items, though I am not sure what else could cause it. Lag perhaps? I've not able to reproduce this at any rate. You weren't trying to do anything else while the progress bar was going I presume?

If you're still getting this please be extremely detailed in the steps you are taking to get it to show up. The type of borg, what modules you have equipped, where you are doing it. Etc. Because right now I've got no clue, nothing looks wrong in the code to me. Unless there is something wrong with `do_after` itself.

**Comment by vinylspiders** [comment]
Going to be closing this one assuming it's not happening regularly. It is likely a timer related issue. Sometimes they break with lag. It's a problem upstream.
