### ISSUE TITLE
Synthetics when gibbed don't drop their POSI anymore.

### ISSUE THREAD

**Issue by avimour** [Skyrat-SS13/Skyrat-TG#20797]
## Testmerges:

[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 64f88e3e09](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#19820: '[TM-ONLY] Prevents the psyker pirate variant from rolling' by GoldenAlpharex at commit b337b1a9a0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
[#20762: 'Peacekeepers Episode Two: Return of the Civil Disputes Officer' by Gandalf2k15 at commit 8a952dabb8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20762)

## Reproduction:

1. Be a synthetic humanoid or find one.
2. Gib them in any manner. Megafauna deaths is the easiest way to do this.
3. Observe as no posi pops out.

A month or so ago this used to not be an issue, posis would spawn after you were gibbed. I should've bug reported this sooner but I completely thought someone else had. Oops.

**Comment by vinylspiders** [comment]
Any idea when this started?

Reading through brain code ironically made my brain HURT. It's ridiculous.

The issue is that for normal brains when you are gibbed, your brain gets put into your head where it can then be removed with with a scalpel.

For some reason, synth brains do NOT get moved into the head like they're supposed to so you aren't able to recover their brains.

I thought this would be a simple fix but the code for moving brains around is incomprehensible and complicated. Going to sit on this one for a bit unless someone else with more familiarity with brain code can fix this.

**Comment by avimour** [comment]
I think the first time I encountered it was...03/27/2023, at around 12:30am EST. I had sent a message about getting gibbed and the posi not spawning at that time.

**Comment by vinylspiders** [comment]
> I think the first time I encountered it was...03/27/2023, at around 12:30am EST. I had sent a message about getting gibbed and the posi not spawning at that time.

Thanks! I'll look into this soon
