### ISSUE TITLE
Fedoras can't store items

### ISSUE THREAD

**Issue by BriareosBlue** [Skyrat-SS13/Skyrat-TG#21143]
Reporting client version: 514.1589

## Round ID:
8366

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [Re-adds MCR cell swapping](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20792)
- [[Like 99% Modular] Soulcatchers](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20576)
- [GPT API Integration + Use cases](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20958)

## Reproduction:

Fedoras can no longer seem to fit items into it. Upon trying to put an item into it, you will be informed that the item cannot fit and that you need to make space, even if there are no items already in the fedora.

**Comment by vinylspiders** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/8ac1eddc-633d-49b7-a7dd-85e1d648e0e6)

Make sure you didn't already put something in it. Alt-click shows the inventory bar.

There was a bug causing the inventory to get filled with an invisible item not too long ago that is now fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/21036.

The server just got an update an hour ago, it could have been that the fix wasn't live at the time of this report. If the issue persists please let me know.
