### ISSUE TITLE
Uncraftable Beef Wellington

### ISSUE THREAD

**Issue by thatguyparker** [Skyrat-SS13/Skyrat-TG#21361]
## Round ID:
8458

## Reproduction:

Attempt to cook a Beef Wellington while having the ingredients. No matter what kind of mushrooms you have, or whatever kinds of meat you got, you cannot create it.

**Comment by vinylspiders** [comment]
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/df5c6620-23e3-41e6-a861-6a937cebd98b)

I just tested this and was able to just fine--you sure you're not trying to make it with a 'pie dough' instead of 'flat dough'? They look very similar.

I used wall mushrooms and monkey steak but I tested with other kinds and they worked as well.

**Comment by thatguyparker** [comment]
I tried this at the time with all of the ingredients but I had Chanterelle and Plump Helmet mushrooms, and had Meatwheat steaks. Could not make it.

**Comment by vinylspiders** [comment]
That's very odd---I've updated my build to the latest and tested it again with Chanterelle, Plump Helmets, and Meatwheat steak. I still was able to cook the Beef Wellington without any issue!

Maybe the pepper mill or salt shaker you were using that round was empty unbeknownst to you? Also the bacon has to be pre- cooked as well as the steak. Raw bacon will NOT work.

I'd try it again and make sure you are doing it correctly with all that in mind. If it's still giving you trouble feel free to comment with the details and I will reopen this.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/cda80168-6efc-47ce-9b7b-54acf54c1be1)
