### ISSUE TITLE
DNR Bypass

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#2188]
Reporting client version: 513.1536

## Round ID:
[225](https://scrubby.melonmesa.com/round/225)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)

## Reproduction:

I'm not entirely sure how someone can bypass it, but medical doctors have recently been able to revive people despite them turning on DNR, resulting in live bodies which the ghost of the person who DNR'd cant enter. 

As for how its done, just ask medical. I don't know how, but i've had my body revived despite having DNR enabled multiple times now.

**Comment by SpookyTheFox** [comment]
Does not seem to be a bug, entirely. You have always been able to force revive bodies even if the ghost is not inside using revival surgery. During a round in which you were the clown, I revived you through the normal process of tending wounds until damage was under 200 total, and then using a defib. Nothing special at all. Got an admin PM telling me you were DNR afterward. *shrug. TG medicine seems to be a lot more lenient with revivals than old citcode skyrat was.

Your job as doctor is not done until the person is revived or in the morgue, and considering that morgue caskets do not seem to have an alarm right now, I'm perfectly happy with bodies just reviving to a catatonic state when the ghost is not present, since that's a firm fulfillment of medical responsibility.

It's an issue for antags though, because catatonic heavily implies they rage-quit and are avoiding IC punishment, rather than staying dead.
