### ISSUE TITLE
UI not appearing (after using GPS?)

### ISSUE THREAD

**Issue by Krypandenej** [Skyrat-SS13/Skyrat-TG#21932]
## Round ID:
8673

[Round ID]: 8673

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [TTS usage check](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [[Semi-modular] (The big) Akula species revamp](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20131)
- [Increased alcohol/nicotine tolerance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21546)
- [[test] more clarity for rails, make rails take longer to connect](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21777)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
- [Makes Podpeople Hair Recolorable 3-D: The Revenge](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19908)

## Reproduction:
I was having a moment mining, and went through the round as usual, grabbing ore and stumbling across some loot - like some loose tendril items - using the already used and replenished fountain, and using the Bluespace Shelter's immobile GPS to mark the spot. When I came up to use the ORM, I failed to trigger the UI... And then tried to use the autolathe, request console, and even point at/climb people, to no avail! Pointing at people just switched my hands, and interacting with the wall-mounted requests console caused me to touch the wall. I believe this MAY have to deal with the GPS, but I'm not sure.

**Comment by Krypandenej** [comment]
UPDATE: FIXED BY TRAVELING TO A NEW Z-LEVEL. Map was Northstar.

**Comment by vinylspiders** [comment]
This is known upstream bug. I've noticed it lately---possibly one of the more recent tgui updates causes it. 

It generally happens when your client disconnects while you have UIs opened. The UI is stuck considered 'open' even though it's not on your screen. 

For now, until they fix it:

By moving enough distance away from the object that creates the UI it will allow the UI to close on its own and be openable again. Which is what you did with moving to another Z-level, though in most cases moving a few tiles away should suffice.

**Comment by vinylspiders** [comment]
Should be fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/22700
