### ISSUE TITLE
Hyper Horny Hound

### ISSUE THREAD

**Issue by SilvertheLynx** [Skyrat-SS13/Skyrat-TG#22146]
Reporting client version: 514.1589

## Round ID:
8760

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)
- [(testmerge only) Makes jetpacks work again](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22045)
- [[MIRROR] TTS Improvements: Improved Audio Quality, Pitch Adjustment, Preference Silicon Voices, Per-Character Voice Disable Toggle, Tongue Voice Filters, Reworked Silicon and Vending Machine Filters [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22120)

## Reproduction: might have something to do with the hypersensitive and sadist quirk?

Truthfully unsure what's causing it, but there's this weird thing that no matter how many times my character reaches a climax they're never satisfied and will continue to be horny. I'm thinking there's some expediential going on with the hypersensitive and the sadism quirk where he'll get excited from a bruise and if i remain there withen the minute i'm max arousal and no matter how many times he "cums" he remains aroused

**Comment by vinylspiders** [comment]
There wouldn't be any interactions between those two quirks---however, if someone is nearby is in pain, then each life tick you will gain 2 arousal, continuously.

I looked into this and found the issue. Basically there is a runtime happening in climax preventing the arousal values from being reset. It will be fixed once the PR is merged. On top of that I made it so that while you have the climax moodlet (lasts 30 seconds) you will not gain more arousal from the sadism quirk. So that should help a bit too. But the main issue was that runtime.
