### ISSUE TITLE
Pocket items don't drop when gibbed.

### ISSUE THREAD

**Issue by Drayco84** [Skyrat-SS13/Skyrat-TG#22299]
## Testmerges:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22045
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21991

## Reproduction:
When gibbed, items in pockets are destroyed instead of dropping onto the ground. This mostly defeats the purpose of even picking up a GPS as **everything else** that's worn is destroyed. Clothes, belt, shoes, backpack, suit item, EVERYTHING.

**Comment by vinylspiders** [comment]
>everything else that's worn is destroyed. Clothes, belt, shoes, backpack, suit item, EVERYTHING.

Actually only things worn on the torso should be getting destroyed. Belt, backpack, pockets, suit item, yes--but anything worn on the extremities gets thrown around when you get gibbed. Like shoes, hats, headsets, gloves--those should not be getting destroyed. That is the default gibbing behavior from upstream.

May I ask what source of gibbing you think should still leave clothing intact? If it doesn't make sense then we could certainly change it to drop all clothing quite easily for that one thing.

The default gibbing behavior supports this and it can be toggled on an individual basis. Monkey cubes for example leave your clothing intact when you eat them and get gibbed that way.

Otherwise this is intentional default behavior with the `gib()` proc I'm afraid. You're asking for an upstream feature change not a bug request in that case.

**Comment by Drayco84** [comment]
I mean that pocket items shouldn't be destroyed on getting gibbed. I accidentally aggro'd Bubblegum that round and noticed that the mining satchel and GPS in my pockets were destroyed along with my shoes and gloves, which you say should've survived. (Headset did, though.)
I'm fully aware that clothing and backpacks are supposed to be destroyed, I'm just pointing out that since items and containers in these slots get destroyed, there needs to be some places where this doesn't happen. I probably wasn't very clear in this regard, and that's on me. Leaving a GPS in a pocket so it doesn't get destroyed is typical advice for miners in case they take on a gibbing megafauna (Which is most of them.) and fail, that way it's easier for somebody to find their head for revival so they're not Round Removed.

**Comment by vinylspiders** [comment]
>I mean that pocket items shouldn't be destroyed on getting gibbed

Was there a time when they didn't? Trying to figure out when this changed if that's the case.

**Comment by vinylspiders** [comment]
Eh, this is a quick enough thing that I'm not going to bother taking it upstream. I'll make it a modular edit unique to here.
