### ISSUE TITLE
Eye emissive only works properly on body size1.0 characters

### ISSUE THREAD

**Issue by ThatGuyPhil** [Skyrat-SS13/Skyrat-TG#22701]
I noticed that for a while now the eyes for my synth dont glow and that the glowing pixels are in the wrong spot.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50330177/61c75a41-7d61-4247-8735-8c48edbda3ff)
Eye emissive pixel is in the wrong spot. the rest of the body emissives work. 

## Round ID:
8992

## Reproduction:
make a character that has a face like mine i guess
snout type: synthetic lizard - barless tertiary under
body size: 1.1
My guess is that the eye emissives dont change for different body scales. The glowing pixel is lower than the eyes as if they are meant for 1.0 body size instead of 1.1

**Comment by ThatGuyPhil** [comment]
Update:
the eye emissives are broken for nonsynth's too. the real issue is the body size of the character.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50330177/7f97720b-f423-407f-bbf0-d83323028e44)

**Comment by vinylspiders** [comment]
>My guess is that the eye emissives dont change for different body scales. The glowing pixel is lower than the eyes as if they are meant for 1.0 body size instead of 1.1

Yeah, it's a known issue. 

It's due to the eye emissives being added to an overlay of the eye overlay, which is added to the head overlay's overlay...and I'm guessing the recent head refactor did not account for that.

I'm working on a fix upstream at the moment for the lying-down emissives issue and am going to see if I can fix this one there as well because they are both caused by the same thing. It will take me a little bit though, as I have to alter the way that mob overlays are drawn.

See https://github.com/Skyrat-SS13/Skyrat-tg/issues/22553
https://github.com/Skyrat-SS13/Skyrat-tg/issues/22553
https://github.com/Skyrat-SS13/Skyrat-tg/issues/22661
