### ISSUE TITLE
INFINITE BLOB SPAWN [NOT A SCAM]

### ISSUE THREAD

**Issue by Snajper202** [Skyrat-SS13/Skyrat-TG#22772]
Reporting client version: 514.1589

## Round ID:
9013

## Testmerges:
- [[SEMI-MODULAR] Roundstart delam panic button](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22145)
- [[MODULAR] Dynamic threat/midround calculation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22409)
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [[MIRROR] Removes TTS voice disable option (Skyrat: Actually makes a functional "None" voice option this time) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22283)
- [[MANUAL MIRROR] Robotic organ and disease improvements](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22631)

## Reproduction:
Buckle up bois because this evil homie just found out an infite blob spawn with proper steps.  Alright so to even start this you need few things.
A) You need a blob event to be triggered and become the blob overmind,
B) You need to die
C) You need to have someone use the soul catcher
D) Profit from infite spawns from the soul catcher

Possible Explanation: Alright so basically the soul catcher was made with carbon bodies in mind, however if you join it as a dead blob overmind, you do not really have any body anymore as such upon clicking the "Return to body" button, the code will fail to find the body as it does not exist and instead will create a new blob core right ontop the poor sod who is holding the soul catcher allowing you to basically spawn over and over multiple times in the round as long as someone have an open soulcatcher tuned for the dead.
There is posibility this is further exploitable by people whose body was anihilated as it opens a posibility of the return to the body button creating a new carbon body that was, lets say cremated.

Post note: Finally showing the staff im usefull for something after collecting so many notes hah. Enjoy the exploit! Cheers o7 Also this is not a singular case only as i managed to verify it with an admin in game in the same round i did the exploit previously.

**Comment by softcerv** [comment]
oh wow, that's wack

**Comment by softcerv** [comment]
Alright, so I did some testing to figure this out, and this is something that is actually an upstream issue. 

Basically, from what I understand the ability to become a blob is actually linked with the mind, so, if we spawn the blob over-mind in as a person after dying using ctrl+shift, we will have this exact same issue. The former blob is only able to do this when a mind is put inside of a new body, and because a soulcatcher soul is a body, this works.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/1c90e8ed-67e4-4ace-90be-838c4119605b)

> There is posibility this is further exploitable by people whose body was anihilated as it opens a posibility of the return to the body button creating a new carbon body that was, lets say cremated.

Your intuition on this was good, but it didn't line up with how the code works. While it does check for a new body, it does not create a new one, *players are not able to use soulcatchers to respawn.* We can also rule out the identity of the dead mob not being a carbon causing this glitch.

**Comment by softcerv** [comment]
The blob antag datum is not cleared from the mind upon the blob dying. This needs to be fixed upstream
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/3cb8d20d-15a2-44d6-8b1c-abcdf6b4c66e)

**Comment by softcerv** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/22915
