### ISSUE TITLE
Nanomachines deleting character variables.

### ISSUE THREAD

**Issue by xXPawnStarrXx** [Skyrat-SS13/Skyrat-tg#2312]
Reporting client version: 513.1530

## Round ID:
[308](https://scrubby.melonmesa.com/round/308)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [Map Vote Fix [TM]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2277)

**Comment by SpookyTheFox** [comment]
Also occurred in round 290. Same thing happened, nanomachine pizza caused three people to be borged, and they received default humans named "cyborg" when the brains were ejected and cloned.

**Comment by YakumoChen** [comment]
Roboburgers containing nanomachines are supposed to borg you, yes. It's a chem-based disease.

**Comment by SpookyTheFox** [comment]
> 
> 
> Roboburgers containing nanomachines are supposed to borg you, yes. It's a chem-based disease.

That I am aware of. It however, is missing some critical functionality. The resulting borg has a generic brain named "cyborg" inside, and when you un-borg that brain, it clones into a generic human. Ideally, what it should be doing, is using the brain of the character it transforms, and keeping their brain in the MMI, so it can be ejected and cloned as an in-character solution to the disease, as well as having the proper name if the borg is destroyed and the MMI ejected intact.

Nanomachines causes a disease, /datum/disease/transformation/robot, which makes them into a /mob/living/silicon/robot. I can't find where it actually transoforms them, but I assume it makes a generic borg and sticks the mind datum in, rather than taking the actual brain of the infected person.

**Comment by Zergspower** [comment]
Issue resolved via SAD Machine after implanting into a new body
