### ISSUE TITLE
Skyrat original foods don't have a complexity and don't tie in with TG food mechanics

### ISSUE THREAD

**Issue by burgerenergy** [Skyrat-SS13/Skyrat-tg#23605]
## Testmerges:

[#22097: '[MODULAR] Adds the option for missing a limb to the prosthetics menu' by lessthnthree at commit bc2a515ce3](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
[#22119: 'Makes the dna's body size feature use `update_transform()`' by Ghommie at commit 488f900320](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22119)
[#23521: 'Adds the ability to make calls from outside the server to modify player ranks live' by GoldenAlpharex at commit 3ca83ded31](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23521)
[#23424: '[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related' by Paxilmaniac at commit 0b083c675d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)

## Reproduction:

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/121744141/242540e9-3681-4d90-b604-19e380bbddbf)

I assume #23440 did this and it wasn't noticed, but soup has no listed complexity now that nutrition is gone.

**Comment by burgerenergy** [comment]
Also; they do not provide the usual complexity based buff, so they're completely out of system.

Edit: Several items in the food menu also do not have complexity. I am willing to assume this means they won't fit nicely with the system, so someone will, unfortunately, have to tiringly go through every single one.

**Comment by vinylspiders** [comment]
Can I ask which Skyrat foods are missing complexity?

I painstakingly went through them all when I was fixing that PR so they -should- all be there. 

It should be noted that (for whatever reason) they made it upstream such that food with a complexity of 0 do not display any complexity. So any foods you see it 'missing' from you can assume are complexity 0. Typically this is raw food that has been minimally processed.

For instance:

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/db123c5c-6811-480e-8031-110ee2068e3a)

You can see blood curd here has complexity of 0

https://github.com/Skyrat-SS13/Skyrat-tg/blob/b47943c7a965f477837385a584f16949171f8d0d/modular_skyrat/modules/customization/modules/food_and_drinks/food/hemophage_food.dm#L80-L90

As for soups not having complexity, that's upstream too. Soups of all kinds (except the 'bowled' items like amanita jelly) are omitted from the complexity system, I'm guessing that's because most soups are not not `obj/item/food` but rather are reagent mixtures. And the recipe complexity var is actually tied to `obj/item/food`, not a reagent.

Maybe they'll add it in the future.

**Comment by vinylspiders** [comment]
Since this was made there has been a PR that adds some more missing complexities upstream. The soup is still not a thing but that is not a bug so much as a feature request, and an upstream one at that.
