### ISSUE TITLE
Telekenistic get you a black box instantly

### ISSUE THREAD

**Issue by NonoodWhatever** [Skyrat-SS13/Skyrat-tg#2427]
Reporting client version: 513.1536

## Round ID:
[385](https://scrubby.melonmesa.com/round/385)

## Testmerges:
- [[TESTMERGE] Makes icon2html not work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/948)
- [[DNM] Cryo on core maps [TESTMERGE ONLY]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1783)
- [[TM] Disables sentient disease - pending rebalancing/tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2030)
- [Makes command immune to FAMILIES](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2175)
- [[Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2180)
- [[WIP] Combat rework - less lethality, less hardstuns, nonlethal takedowns. Focus on combat ineffectivity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285)
- [Assault Operatives + Skyrat Modular Map System [READY FOR TESTING, MODULAR]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2317)
- [Brig timers now calculate from real time, not time dilation time. You can set brig timers to 60 minutes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1939)
- [[TM READY] Ghost roles can now be configured to allow people using their prefs character. Allows this for a good chunk of ghosties](https://github.com/Skyrat-SS13/Skyrat-tg/pull/2341)

## Reproduction:
1. Get telekinesis gene up, either by mutating or activating.
2. Get yourself a X-ray eye.  Night vision goggle can assist the expliot if the black box recorder is in dark area.
3. Click at the black box recorder, if you are close to black box recorder, you didn't make expliolt. Can be done across the wall in enclosed area.
4. Black box in hand instead of on the blackbox recorder itself.

I recommend that you try other things too, like vending machines.

**Comment by unit0016** [comment]
This same thing happens with using MMIs / bluespace bodybags inhand using TK too. It's an upstream issue, though, not a skrat one.

**Comment by AlinaStarkova** [comment]
ah yeah this is probably an issue with the way TK is actually coded, TK has always functioned as a hand that you can use anywhere you can see, so some items like black box, mmis etc.. pop the item out into your hand, but since the TK is probably only coded as an extension of your hand and not a hand itself, the only valid hand for those things to be placed, is in the hand TK is used from. not sure on if a fix for this would be easy, perhaps the easiest would just disable TK from being able to activate things which place items into your hand. ill mention this upstream

added an issue report upstream for this

**Comment by atakiya** [comment]
Should be fixed by #2496
