### ISSUE TITLE
Tactical skirtleneck/research director's skirtleneck don't appear correctly on digitigrade legs

### ISSUE THREAD

**Issue by Ducky-Momo** [Skyrat-SS13/Skyrat-tg#3608]
## Reproduction:

1) Be a lizard with digitigrade legs
2) Try to wear a tactical skirtleneck/research director's skirtleneck
3) Watch as it doesn't appear and SUIT hovers near your sprite.

**Comment by Zergspower** [comment]
![image](https://user-images.githubusercontent.com/22140677/158647259-474cc8ba-2943-4429-a5db-7bf6d206c3f7.png)
I wore a skirt for this - unable to reproduce bug and with how old it is it's safe to assume it was fixed. the weird thing is the sprite is the science sprite instead of the brown suit however
