### ISSUE TITLE
Janitoral Toolset Implant is broken

### ISSUE THREAD

**Issue by unit0016** [Skyrat-SS13/Skyrat-tg#6361]
Reporting client version: 513.1542

## Round ID:
2095

## Testmerges:
- [[TM-ONLY] Pellet cloud tweaks](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6257)
- [S&T Additional Emotes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6259)
- [Sec fine tunes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6354)

## Reproduction:
Install janitorial toolset implant
use it
cry when it doesn't work

**Comment by SpookyTheFox** [comment]
I'm working on this one today. So far, I have discovered that the botany arm tool set implant and hacker arm tool set implant are also broken. I believe the culprit to be either lists or radial menus specifically for implants in that modular folder, as the normal tool set and surgical tool set implants are not affected. This is further supported by my testing with the mantis blade implant, which works until you emag it. This makes sense, because it gains another item and should have a radial menu after emagging. Thus, I am fairly confident in saying that radial menus or lists are not working correctly for these modular implants.

**Comment by SpookyTheFox** [comment]
As an update, it seems #6252 changed the way lists inside implants work, among other things. The fix is fairly simple, I'll get it going. I just need to make all the
`contents = newlist()`
into
`items_to_create = list()`
For every multi-item implant. Single item implants can apparently fall back, but there's an edge case with emagged implants I need to look at as well.

**Comment by SpookyTheFox** [comment]
And here it is. #6352
