### ISSUE TITLE
The AI can see syndicate borgs on the syndicate base, as well as the syndicate xenobiology camera.

### ISSUE THREAD

**Issue by BurgerLUA** [Skyrat-SS13/Skyrat-tg#7394]
Reporting client version: 513.1542

## Round ID:
2595

## Testmerges:
- [[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6478)
- [Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7173)
- [The final nail in the unfun round removal coffin](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6943)
- [[MODULAR] New species: Ghouls](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6928)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[DNM] [TEST-MERGE-ONLY] Time to find out what's going on with outfits.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7305)
- [[NON-MODULAR] Runtime Begone](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7357)
- [[semi-modular] reagent forge](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6643)
- [[semi-modular] xenoarch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6671)

## Reproduction:

Be AI.
Get sent emotes by Syndicate dogborg erp.
Track erper with camera.
See syndicate erping near xenobio console.
Cry

**Comment by unit0016** [comment]
Who added the ability to see emotes through the AI eye again? At this point it's becoming a personal problem.

**Comment by SpookyTheFox** [comment]
AI receiving unwanted emotes is bad. And they seem to come from xenobio cameras in particular, so you get spammed with slime emotes.

The problem with ghost roles building borgs, is that there's no separate camera or AI networks, multiple factions making borgs was simply never intended. I can't see any in character and player facing way to remedy this, that wouldn't be open to effortless and severe abuse. There are however, good work arounds for ghost roles, all of which revolve around scrambled codes. Those options are:

- Ask for admins to use the borg panel to give "scrambled codes"
- Run /mob/living/silicon/robot/proc/UnlinkSelf() on the borg, which is what ninja conversion does
- Give them a syndicate borg upgrade card, which gives scrambled codes when used
- give them a nukie borg spawner.
Nukie borg spawn beacon is probably the safest bet, safe enough to leave in maps. It runs the same check as nukies using S-pins and getting ignored by syndicate themed mobs. Last I looked, the syndicate ghost roles had the appropriate flag, but even station traitors won't have it, and thus, can't use a nukie borg beacon even if they get hold of it. The down side to using nukie borgs for ghost roles, is no dog borg options, and the beacon requires the antag pref for operative to be enabled to see the prompt as a ghost. So, they might not get many takers. The only option that lets them stay  dog borgs, is using the admin borg panel to set scrambled codes. Since scrambled codes kills the camera link, it hopefully also prevents the AI from seeing those emotes.

**Comment by unit0016** [comment]
@BurgerLUA @SpookyTheFox I've discovered what I think is probable cause for this and #7489 (Which are the same issue, but twice essentially.)

The PR that made it so the AI eye can see emotes didn't check specifically for the player's "eye" - rather it checked for ANY existing AI eye, and even their subtypes. This includes advanced camera consoles, which include shuttle docking consoles and even xenobiology console!

You. May see the problem.

**Comment by FlamingLily** [comment]
Fixed https://github.com/Skyrat-SS13/Skyrat-tg/pull/7621
