### ISSUE TITLE
Fireplaces are hilariously deadly

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#8216]
## Round ID:
3017

## Reproduction:

Put some wood in a fireplace
Die a couple minutes later from co2

Fireplaces are absurdly deadly for no real good reason, Not even bonfires, I mean just the furniture that makes a light and doesn't really heat anything. A small room had 500kpa room temp air of just co2 after burning through its wood supply, and nearly killed me and another person from inhalation. 

Why add this feature? I shouldn't need an air filter machine just to enjoy a fireplace. It didn't do this before.

@Gandalf2k15

**Comment by Seris02** [comment]
this should probably be closed

**Comment by YakumoChen** [comment]
@Seris02 I've yet to see proof that this was fixed since I haven't seen any PRs touching pollution

**Comment by Seris02** [comment]
Ah, wait, nevermind, I was being a bit dumb

**Comment by GoldenAlpharex** [comment]
I don't see any mention of the pollution component on the fireplaces, so I don't think this is actually a feature there.

The CO2 was likely due to you breathing and the air not being cycled in the cabin. Other than that, it could've also possibly been caused by someone stepping through the front door.

Send in a message here or open another issue if it's still happening.
