### ISSUE TITLE
Feature Request Mega(Not really)-List

### ISSUE THREAD

**Issue by ShadeAware** [Skyrat-SS13/Skyrat-tg#887]
### Items will be removed as they are addressed.

- **PLEASE** for the love of God get rid of random item placement when you drop shit. Not being able to put things like cyborg shells directly in the middle of the tile is scraping at my OCD to no end.

- **I really fucking miss being able to sprint.**

- Lots of things are super over-buffed when it comes to deconstruction steps. A reinforced window takes more steps and effort to deconstruct than a fucking **reinforced wall.**

- _**IMPORTANT BOBMED FEATURES LIKE DECAPITATION WOUNDS, SYNTHETIC WOUNDS, AND SEPARATED LIMBS ARE ALL MISSING (!!!!!!!!!)**_

**Comment by Addirem** [comment]
I agree with you on everything here except the smooth movement. 
In addition, I would greatly enjoy a large amount of changed, specifically to medical, to make it more similar to what we have now, at least towards chemistry being brought back to how we have it, alongside cloning being brought back. 
In addition, I'd like to see our custom drinks ported over.

**Comment by Hemlock32** [comment]
-The new lighting looks like any other codebase, and, I feel like the super detailed lighting is partially contributing to the lag. If it's not, then, sure, port it, but, it feels like a non-issue to me, as, like I said, that's what other codebases look like, and, tbh, your Eris walls would probably look better with this lighting.
-Smooth movement really feels like it would be a waste of effort to change. Too much work to undo a subjective thing that most people probably like and isn't that much of consequence.
-I haven't noticed any outdated textures. APCs, and tables look the same, and, the tool texture changes are an improvement over what CitCode has, and, I'd prefer one of the many tool texture replacer projects to come in rather than reverting to CitCode tool sprites
-The border around the screen is likely to do with TG's new chat/tab UI, and, feels like it would be worth more effort to get rid of than its worth, but, if it can go without bugs and tedium, then sure
-Sprint involves stamina being added back (Unless the stamina buffer is the only limit on sprinting), and, I don't want that. Plus, faster movement often leads to more clunky combat, and, security chases being a guessing game of who went what direction, and just in general a a large amount of balance issues.
-You complain about no sprinting, then complain about faster non-sprinting speed? I personally prefer moving slightly faster while running, without sprints extreme speed and constantly holding shift and monitoring the sprint buffer.

-Cloning is getting a hard "PLEASE GOD NO" from me. This server already has respawning, which, is more than most servers allow. I'd rather just slow the speed of organ rot.
And, what's so different about medbay? I've seen nothing but improvements so far to its layout and the mechanics around it. Things like the scanner machine, the chemistry plumbing are something I very much think is a good change, as, it gives chemists and medbay both something to do and a reward for it

**Comment by ShadeAware** [comment]
-Atrocious lighting like TG is nothing like any other codebase I've played. Its washed out and outdated, and is somehow simultaneously too dim and looks like the gamma is set way too high.
-Removing smooth movement is not wasted effort. You don't want to have movement feel like a floaty roller-skating mess, because then nobody would want to play it like that. Also, almost nobody likes it.
-You're genuinely blind, because they look entirely different and worse. Tools are more subjective and a nonissue, really.
-Sprint was better than what TG has now. Right now, you have a choice bewteen: 1. Moving at supersonic speeds; 2. Crawling about 1 nanometer a minute. This isn't fun or good in any respect. The previous choice between creeping, a decent walk, and running was **infinitely better.**

**Comment by YakumoChen** [comment]
rwindow buffs were to stop people from constantly breaking into places with no difficulty, which is probably less of a problem on SR

Light subsystem is incredibly laggy, probably the laggiest subsystem in the game right now. Simplifying it more would probably be much better for server health.

**Comment by Azarak** [comment]
Light is far away from being performance heavy ever since overlay lighting is a thing, it is still a heavy memory sink though. The light changes to power and color dont really affect its processing too much, and that's the only difference from the TG and Cit base

**Comment by atakiya** [comment]
Closing due to most issues being resolved and this being stale.
If there are still issues, please open new feature request or bug reports, with one issue per feature/bug, thank you.
