### ISSUE TITLE
'Features' and things we currently have on the main server 

### ISSUE THREAD

**Issue by IrkallaEpsilon** [Skyrat-SS13/Skyrat-tg#900]
Long list. Lots of explanation behind on why I think this should be ported. 

In order of priority, lots of it is just me trying to explain why:
-2: Exploitable Info, Custom objectives and crew records (General, Medical and Security), Reason: Fuck TG objectives, would be nice if cool antag boys that try make the round fun for others have something to work with and crew records because some people do really like to set them. Maybe be able to set race name so we arent stuck with TG names. I know a few people that would appreciate it but not really needed. Also Cafe for undisturbed (E)RP. Also more than 3 character slots. We have.. 30(?) on main.

-1: No head antags, QM to heads. All that effort and all that work and you decide to pull a fast one to go get the thermal drill and heist the vault? Instant trust with heads, RD antags are a nightmare, CE antags are a nightmare, now imagine if we had sec antags that simply go for "You arrested" and then just do the epic John Wick objective. Which brings me to the next one.

0. : Comment out assassinate and kill objectives. Probs make them opt in/opt out.

Reason: I had it with this powergame, grudge and validhunt catalyst. People can use custom objectives. If somebody wants to be involved in direct assassination stuff: They can put it in exploitable. I think thats why a guy initially paid a dude to get this ported from bay/Hestia anyhow. Worked super well on Hestia. Probs better to hard remove these objectives so no gamemode can ever roll them. Heres again the reason behind my way of thinking: Assassinate objectives are the most effective powergame, validhunt and grudge catalysts. This objective brings out the worst in people. You dont bother interacting with your coworkers anymore because if you dont know them OOCly they might just be up to do some shitty objective they set for themself or got assigned to without much thought. This results in people having the 2 tiles distance thing one observes on Para, Fulp, TG aswell as people having roundstart rituals like making the incredibly powergamy spray bottle of anti assassin (ClF3, Napalm, Lube) among other fun things. The game takes on a TTT like tone which is good for LRP like TG but poison to anything aiming for higher standards. Blueshields will take the "tactical locker" on bridge to block bullets for Captain if some guy rolls in for the fifteeth time this week with a TG style assassinate objective. Sec wont bother talking because alot of them can and will relate to the person that basicly got merced and just shoot to kill in the most gamy way possible. The Victims will get highly upset at sec if they decide to not execute the guy that merced them. Its simply a cascading effect we can opt out by simply not having these objectives coded into the game. If somebody loves getting involved in these plots they put it in exploitable. Plenty of people did on Hestia. It worked really well there when it was rather popular. We had tons of quality antags. Then devs stopped working due to baycode and Carl pulled the plug. "JuSt ReSpAwN" does not fix it. The damage is done regardless if you can respawn. This thing makes people jaded and not want to interact with anyone and do their own thing if that keeps happening out of the blue. And no "its just a slim chance" is not an excuse. The chance is there and thats enough for people to act like well.. they are in a game of TTT. Undirected Antagonism > Directed Antagonism. Heck I honestly rather have a murderhobo than yet another assassin gimmick but thats just personal opinion :').

Other than that on this entire thing: Not all of us get to play 4-5 rounds a day. Some get maybe half a round at most. Some have other things to do. People should not need to sacrifice their round for somebodies shitty ass permakill objective they did not bother to change just so they can respawn as a secondary character as epic lawyer/assistant/botanist.

1. Comment out Split Personality Reason: Heavily concerns due to how it will cause ahelps and be genuinly only used to "meme" and "grief", remove brain damage lines (4th wall breaks, LRP) --> We have this removed on main. Split personality ahelps are one of the more unfun and stressful things to deal with when the split deals like a genuine shitter (Yes they do most of the time.).

2. Comment out "Random X" events, specially random brain trauma, they fuck over a single person and contribute nothing to the round. Radiation storm contribute more. Hallucinations contribute more. Electrical overload contributes more. --> We have the Random X event being defunct on main and Brain Trauma commented out. Literally any other event is better.

3. Revert BOH anomaly requirement: Bad for the game, RNG is a bad balancing mechanic, this is CDDA game design if you ask me and we all know how people handle CDDA: They pick the build they like, remove the realism and RNG nerfs and then play it like it used to. Or you get a bunch of people that exploit the next best thing. People dont use anomaly cores even if they have them cause they are "scarce" or were made aware that they are "scarce". People being aware that something is a "rarety" makes them not want to use it.

4. Revert some of the other questionable changes (Removal of Singulo, tesla should be back in black, again CDDA game design is a bad example on how to make changes, botanies disk rack thingy and in general what botany has turned into is yikes.)

5. Revert racist pay: Everyone has to get the same paygrade, appropiate for their job, no matter race, we are a furry server, Lizzer CMOs should get the same pay as Moffs CMOs, Canine CMOs, Human CMOs.

6. Port deep rooted brain trauma fixable with lobotomy without worsening chance, aka no permanent brain traumas. Brain traumas are attached to far too many things. Including things that should not cause physical brain traumas (abductors --> This should cause psychological traumas.. not physical ones, they are far too advanced to fuck up that "trivial shit")

7. Add wizard changes maybe (no: Staff/Wand of Tranformation/Chaos, Instant Gib hand, Mindswap, Summon events ( WARNING GRAPHIC DESCRIPTION DO NOT READ: 
`I love being mindswapped into a scene that breaks personal ERP prefs to the point I would love to scream while a very very detailed emote was posted in dorms 3 or something equal that I wouldnt like to see while the floor tiles were pried off and the toilet was moved to the entrance hallway for some reason` 
GRAPHIC DESCRIPTION STOP DO READ AFTER THIS), Barnyard Curse, Insanity curse (Insanity curse is fundamentally broken for long rounds PERMANENT brain traumas that have the magic tag (literally not fixable bar aheal), also fourth wall breaks)) --> This could make wizard actually happen in normal rotation without people going "Kill wiz call shuttle"

8. Comment out wisdom cow: Fourth wall breaks

9. AI to Crewsimov (Probs done already, reason is obvious)

10. Fix midround events announcement to be less LRP: I can do that, just need an explanation on how to modularize things. Events in question are: Major Spacedust (Neighbour station throws rocks --> Makes no sense ICly), Sentient Animal (Make it just say "A bioscan revealed that one of the stations lesser creatures gained sentience." or alternatively "NT Psicorps Update: A lesser creature on your station gained sentience), Rat migration/mice migration: Remove any ragnarok reference or "space being cold" just make it say: "Bioscans indicate that several rodents are populating maintenance, handle them before it starts affecting productivity", the SM portal event is literally bad SCP shit, can we get that rewritten theres no reason to put [REDACTED] in an official announcement or in anything you send for somebody to read. You would not mention it in the first place so no questions are asked. Arbitrary naming of cataclysm event in the report that is an SCP ref and FAR too large in terms of how its explained. It more or less says the universe is fucked if the event isnt stopped. There are most likely more stations than just this using a magic crystal of power. It implies that this can happen to any SM crystal. In other words somebody would be bound to fuck up somewhere. Short version: Ruins immersion as this kind of scenario would fuck the universe sideways if this aint getting rephrased.

11. Make space dragons not PKers that spawn 20 mins in. ACTUALLY: It vores people. That doesnt make it better and will get people very sad because "vOrE iSnT mY FeTisH wTF". Make it put them into a bluespace portal or some shite. Legit just rephrase it, it gives corpses back on kill afaik, akin to a slaughterdemon on Paracode. I do know a Moff that would like the space dragon though. 

12. Meteors early warning port

13. Disable Cult until reworked, disable Nuke Op till reworked/changed into mercs, maybe disable wizard till its not a "Kill wiz then call shuttle" kind of deal, perhaps get the heretic changes in we were trying ont he main server but never seemed to work properly, maybe they do now dunno. And please completely remove Revolution. Instantanous conversion with no effort, bad IFF in an overglorified TDM, literally "Duh huh kill other party" and the minor reason: Makes no sense ICly. Instantanous, effective and concealable mind control would have been definitly be abused by whoever found out about this one. And probs upscaled. 

14. SUPER HIGH PRIORITY: *weh *merp *nya *bark *hiss, maybe Cits lizard screams they sound cute, TGs deathrattle sounds sound really off but thats probs just me. Also traits: Cold Blooded. Would be nice to have.

15. Some (not all) of the colorful traitor items we got on main.

I rather discuss this stuff further in DMs, I have no notifications for github.

**Comment by Addirem** [comment]
I disagree with -1. We claim to be a M-HRP server, and therefore that gives us more reason for heads to be antags, not less. Frankly I'm confused as to why they can't already be. If we're M-HRP, we should have things that prove it.

**Comment by Gandalf2k15** [comment]
14 is done.

**Comment by Hemlock32** [comment]
I disagree with 3, 4 and **_14_**
Furry emotes bad

Jokes aside though, I feel
3, Science should be able to get anomaly cores through more means, I feel this is an opportunity (To make Xeno-arch more useful) rather than an annoying feature that needs removal.
Some codebases have anomaly research labs, and, they find anomalies through Xeno-archaeology and then using the various machines in the research labs after finding anomalous items to find out what the anomalies do. That's not necessarily exactly what I'm suggesting, but, rather: I feel like adding anomalies to Xeno-arch, is a much better option than having Xeno-arch be all about getting stuff like shields, boxing gloves on a stick, synthesizers and FUCKING DICE OF FATE AAAA, because, as it stands, if the anomaly requirement is removed, that's that issue resolved, yes, but, Xeno-arch is still a useless gimmick. This situation brings up an opportunity to fix two problems by adding, rather than one problem by removing.

4, Absolutely agree on the engine stuff. 
However, I feel like, botany could do with changes. I find it strange and kinda LRP that, a civilian gardening department is making a bunch of weird experimental plants with scientific equipment, that, end up being memes most of the time, like, acidic plants, instant-crit plants, bluespace plants that teleport people they hit or that eat them
I feel old botany could be added if changes were made
Botany becomes part of science, like how robotics is. It could also be a part of science/service both like how mining has 
both science/cargo comms access or how Brig Phys is medical/security. 
Botany and Xenobotany could also be full split, though, that would require a lot of mapping, but, come with the added benefit of allowing players that want to garden without all the experimental stuff a job.
I've also heard about Ambrosia Gaia being gone, and, I'll be honest, part of me thinks that, if it's added back at all, it should be changed to only provide infinite nutriment, not water or stopping weeds. And farm-bots could be added, which, are on other codebases already, so, they'd be easy to make. Basically a water tank turned into a bot with an arm, bucket and plant analyzer that goes around automatically refilling water from water sources and then watering plants that need water, and taking out weeds. This would give robotics something to do, as well as make botany and robotics interact with each other, and, would make botany less of a _rush Gaia round start then botany is easy mode from then on_ weird meta thing
Plus, I see that botany tends to be the ones making teleportation lockers most of the time, and, that feels like it's more a science thing rather than a civilian service thing. 
All-in-all, botany already feels like part of science, acts like part of science, and, on most maps (Especially the most frequently played ones), is right next to science. TG changed to to be more proper civilian gardening. If you're planning on bringing back the old botany stuff, make it part of science.

**Comment by Addirem** [comment]
Botany should be part of science in my honest opinion. It's NOT a civilian gardening thing, at least that's not how it feels. There's a reason the job title is called Botanist and not Gardener by default. There's also a reason that there's a recreational garden with dirt piles on most maps. I very  much feel like we should keep our DNA manipulation botany.

**Comment by Owai-Seek** [comment]
In regards to ThatGuyFromThatPlace's comment on (4).

I think keeping the TG changes while -also- bringing back the DNA Manipulator/Gaia would be fine. Cross pollination, from what it looks like in the TG botany guide, balances all adjacent plant stats over time. It only transfers "Chemical Traits" from other plants if it's fairly unstable. (I assume this means the plants "Reagent Production", not actual "Traits., which are done via grafts.) 

Giving science even more things to play with, while -also- taking it away from botany, would be really lame. Each department usually has a cool experimental thing to toy with, and for Service, that's botany. In addition, "good" botanists would just, steal, print, or ask for DNA manipulator boards, the same thing they do with chem machines.

As for the teleportation lockers, they're only made by one or two botanists who know the specific chem that does it, and as far as I know, it's a fermichem that isn't blacklisted from strange seeds.

~

As for the other suggestions, I basically feel the same. (2) and (3) I have... minor? opinions on.

(2)
Random single person events (Namely, some of the medical ones, such as heart attacks, and appendicitis) do sometimes end up fucking people over. Most of the time it's a nuisance, but I -have- gotten stories out of it before. Pretty funny ones at that. That being said, severe ones like brain trauma, seem a bit much.

(3)
I have personally, like, never ever used extended storages unless they're offered to me as a reward. I work things out with toolbelts or boxes. There's also durathread items as an alternative, but I'm not sure the extended duffelbags are on TG code? I  don't think -everyone- needs easy access/printable storage, but that's just me.

**Comment by Hemlock32** [comment]
> In regards to ThatGuyFromThatPlace's comment on (4).
> 
> I think keeping the TG changes while -also- bringing back the DNA Manipulator/Gaia would be fine. Cross pollination, from what it looks like in the TG botany guide, balances all adjacent plant stats over time. It only transfers "Chemical Traits" from other plants if it's fairly unstable. (I assume this means the plants "Reagent Production", not actual "Traits., which are done via grafts.)
> 
> Giving science even more things to play with, while -also- taking it away from botany, would be really lame. Each department usually has a cool experimental thing to toy with, and for Service, that's botany. In addition, "good" botanists would just, steal, print, or ask for DNA manipulator boards, the same thing they do with chem machines.
> 
> As for the teleportation lockers, they're only made by one or two botanists who know the specific chem that does it, and as far as I know, it's a fermichem that isn't blacklisted from strange seeds.
> 
> ~
> 
> As for the other suggestions, I basically feel the same. (2) and (3) I have... minor? opinions on.
> 
> (2)
> Random single person events (Namely, some of the medical ones, such as heart attacks, and appendicitis) do sometimes end up fucking people over. Most of the time it's a nuisance, but I -have- gotten stories out of it before. Pretty funny ones at that. That being said, severe ones like brain trauma, seem a bit much.
> 
> (3)
> I have personally, like, never ever used extended storages unless they're offered to me as a reward. I work things out with toolbelts or boxes. There's also durathread items as an alternative, but I'm not sure the extended duffelbags are on TG code? I don't think -everyone- needs easy access/printable storage, but that's just me.

You clearly misunderstood what I was saying
To clarify, I never said to take anything away from botany. I said Botany should become part of Science
Because, botany is doing experiments and wacky science shit more than they are actually producing food most of the time, and, it feels really weird that botany, a civilian department, is doing that.
And, if that is to keep up, I think botany should be service/science, like how brig physician is med/sec

And, after looking more into TG botany, I have a few things to add, and, a few statements to retract from my initial post in that, I don't think anything from old botany should be added

I don't think the DNA machines need to be added back in **_at all_**, because, grafting and cross-pollination exists https://tgstation13.org/wiki/Guide_to_hydroponics#Advanced_Botany, and, DNA machines serve literally the same purpose but in a more simplified manner when you compare them side-by-side. Adding them back would be redundant.

Gaia makes botany an AFK simulator with no interaction, and, I don't think it should be a thing, and, once again, modern TG botany has it's alternative to it https://tgstation13.org/wiki/Guide_to_hydroponics#Autogrow_Mode https://tgstation13.org/wiki/Guide_to_hydroponics#Connecting_Trays_with_Plumbing (Plumbing makes a my earlier farmbot idea redundant, but, once again, more interaction than slapping Gaia into every tray and being done) that actually has a cost to it, and requires botany to actively do something to make use of it that isn't bum rushing chemistry roundstart and stealing the chem dispenser like a greytider or annoy the hell out of any and everyone to get chem dispenser boards, but, rather doing stuff themselves or talking with Xenobio to get a yellow slime core (Which is another reason that making them part of science would be a good thing, as, that would cut down on the annoying people thing, and, just be departmental cooperation)

**Comment by atakiya** [comment]
Closing due to most issues being resolved and this being stale.
If there are still issues, please open new feature request or bug reports, with one issue per feature/bug, thank you.
