### ISSUE TITLE
Shotguns can't be loaded with technologicall shells.

### ISSUE THREAD

**Issue by Prusski** [Skyrat-SS13/Skyrat-TG#9472]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
All security shotguns are 14 gauge now, so they can't be loaded with craftable (Technologicall shell) ammo, because those shells from techfab are still 12 gauge.

**Comment by OolongCow** [comment]
I honestly have no idea why someone would create entirely new ammo and replace what all the old shotguns use with it instead of just changing the values and names of the previous ammo types. It's just messy and serves zero purpose except to excuse them from changing the ammo that things like ERTs and nukies use.

I'll work on writing the 14 gauge changes over the old ammunition types this weekend if I have the time.

**Comment by Zergspower** [comment]
Seems to have been resolved over time
