### ISSUE TITLE
Interdyne Self Destruct does not actually destruct anything of value

### ISSUE THREAD

**Issue by YakumoChen** [Skyrat-SS13/Skyrat-TG#9678]
## Reproduction:
Interdyne, a child of the old Syndicate Mining Base, has a very large footprint. 

There's a bomb in the middle, but the bomb is located in a hub with a huge amount of 'white space' between it any other 'pods'. The explosion typically does nothing but damage the central spoke of the base, while causing no damage whatsoever to any parts of the base that have value.

Traditionally the Syndie Minebase has 'explosive walls' that are triggered by the self-destruct device, causing the whole base to be wiped, but Interdyne has no such thing. But besides that, it is too large and open for the bomb to delete any 'research' the base is conducting, making the bomb's existence in the center very pointless.

**Comment by Ebin-Halcyon** [comment]
Reason explosive walls were removed in the first place was Colossus deathbolts/gibto setting off explosive walls prematurely because we've had **this** happen far too many times to count.

![image](https://user-images.githubusercontent.com/81479835/143772015-53fa5148-942e-4dfc-8065-daa8427d1e11.png)

If you wanna code new explosive walls that don't get set off if a Colossus sneezes at us or a stray gibtonite blast a miner set off, be my guest.

**Comment by YakumoChen** [comment]
it sounds like it would be easy enough to code the walls to only trigger to the syndie bomb explosion, or to just make a new object that triggers the walls to explode instead of a syndiebomb.

Or just remap it because the base is way too large, put "stuff the bomb would want to blow" closer to the actual bomb.

**Comment by Zergspower** [comment]
no issue really present, upstream can fix their version but SR's is never at the point of it being needed except a funny during EORG
